/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-20 05:52:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

		request.setCharacterEncoding("EUC-KR");
		String id = (String)session.getAttribute("idKey");


      out.write("\r\n");
      out.write("<!--<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>-->\r\n");
      out.write("\t\t<meta charset=\"EUC-KR\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/top.css\">\r\n");
      out.write("\t\t<script src=\"https://kit.fontawesome.com/115bcf1f34.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("    <!--</head>\r\n");
      out.write("\t<body> -->\r\n");
      out.write("\t        \r\n");
      out.write("\t\t\t    <div id=\"wrap\" style=\"display:none;border:1px solid #DDDDDD;width:500px;margin-top:500px; margin-left: 200px, z-index: 200\"></div>\r\n");
      out.write("    \t<div style=\"height:10px;\"></div>\r\n");
      out.write("\t    <div id=\"modalDiv\">\r\n");
      out.write("\t        <div id=\"modalInnerFrame\">\r\n");
      out.write("\t\t\t\t<div id=\"modal_elements_wrapper\">\r\n");
      out.write("\t\t\t\t\t<!-- modal_header : 로그인 / 회원가입 버튼-->\r\n");
      out.write("\t\t\t\t\t<div id=\"modal_header\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"login_btn\" class=\"login_signup_btns\" name=\"login_signup_btns\" onclick=\"login_signup('login')\" checked>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"login_btn\" id=\"login_btn_label\" class=\"login_signup_btns_label\" >&nbsp로그인&nbsp</label>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"modal_header_span\">&nbsp&nbsp&nbsp&nbsp&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"signup_btn\" class=\"login_signup_btns\" name=\"login_signup_btns\" onclick=\"login_signup('signup')\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"signup_btn\" id=\"signup_btn_label\" class=\"login_signup_btns_label\">회원가입</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form method=\"POST\" id=\"login_form\" action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<h3>어서오세요!</h3>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"login_id_input\" class=\"login_input\" name=\"id\" placeholder=\"아이디를 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"login_pwd_input\" class=\"login_input\" name=\"pwd\" placeholder=\"비밀번호를 입력해주세요.\"autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"lost_id_pwd_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">아이디나 비밀번호를 잊어버렸습니까?</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"top_modal_button top_modal_button_style top_modal_orange\" id=\"login_submit_btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"login_span\">로그인</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form id=\"signup_form\">\r\n");
      out.write("\t\t\t\t\t\t<h3>처음이세요?</h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"daumWrap\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"id_section\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"signup_input\" id=\"id_section_input\" autocomplete=\"off\" placeholder=\"아이디를 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- ajax 필요 ?-->\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"signup_util_btn top_modal_button_style top_modal_orange top_modal_button\" id=\"id_section_btn\"><span>중복확인</span></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"signup_input signup_long_input\" id=\"signup_pwd\"autocomplete=\"off\" placeholder=\"비밀번호를 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"signup_input signup_long_input\" id=\"signup_pwd_check\" autocomplete=\"off\" placeholder=\"비밀번호를 한번 더 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_name\" autocomplete=\"off\" placeholder=\"이름을 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_birth\" autocomplete=\"off\" placeholder=\"생년월일을 입력하세요. Ex)1900-01-01\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_email\" autocomplete=\"off\" placeholder=\"이메일을 입력하세요. Ex)timi2030@gmail.com\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_phone\" autocomplete=\"off\" placeholder=\"연락처를 입력하세요. Ex)010-0000-0000\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"address_section\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id =\"address_section_header\">\r\n");
      out.write("\t\t\t\t\t\t\t    <input id=\"address_section_zipcode\" class=\"signup_input\" type=\"text\" value=\"\" readOnly/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"address_section_btn\" class=\"signup_util_btn top_modal_button_style top_modal_button\" onclick=\"openDaumZipAddress();\"><span>주소 찾기</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    <!-- 다음 우편번호 찾기 리스트를 띄울 영역을 지정 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    <input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_addr\" readOnly/>\r\n");
      out.write("\t\t\t\t\t\t\t    <input type=\"text\" class=\"signup_input signup_long_input\" id=\"signup_addr_detail\" placeholder=\"상세주소를 입력하세요.\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"top_modal_button top_modal_button_style top_modal_orange\" id=\"signup_submit_btn\" >\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"submit_span\" class=\"box\">회원가입</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <label for=\"userPopup\"></label>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \t    <!--전체 페이지 Wrapper-->\r\n");
      out.write("\t    <div id=\"top_wrapper\">\r\n");
      out.write("\t        <!--header Wrapper(로고 상단 Div(추가 Contents 대비용), Hompage Logo)-->\r\n");
      out.write("\t        <div id=\"header\">\r\n");
      out.write("\t            <!--ADD CONTENTS-->\r\n");
      out.write("\t            <div id=\"headerTopMenu\">\r\n");
      out.write("\t                <!--필요시 문의-->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!--로고 이미지 Div-->\r\n");
      out.write("\t            <div id=\"homeLogo\">\r\n");
      out.write("\t            \t<a id=\"logo_a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\r\n");
      out.write("\t\t                <img id=\"logoImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/index/logo/mills_logo.png\" alt=\"이미지 로딩 불가!\">\r\n");
      out.write("\t\t                <!--LOGO-->\r\n");
      out.write("\t            \t</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div id=\"search_div\">\r\n");
      out.write("\t                <form  id=\"search_form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/goods_list.jsp\">\r\n");
      out.write("\t                    <label>\r\n");
      out.write("\t                        <input name=\"searchTerm\" type=\"text\" id=\"search_input\" placeholder=\"상품을 입력하세요\" autocomplete=”off”>\r\n");
      out.write("\t                        <i class=\"fas fa-search\" onclick=\"document.getElementById('search_form').submit()\"></i>\r\n");
      out.write("\t                    </label>\r\n");
      out.write("\t                        <input name=\"list\" value=\"search\" type=\"hidden\">\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <!--메뉴 네비게이션(sticky)-->\r\n");
      out.write("\t        <div id=\"menuNav\">\r\n");
      out.write("\t            <!--nav 구성 :1개의 슬라이드 메뉴, 베스트, 신상품, 고객지원, 검색창(search icon), shopping icon(장바구니)-->\r\n");
      out.write("\t            <div id=\"nav_Div\">\r\n");
      out.write("\t                <ul class=\"nav_main\">\r\n");
      out.write("\t                    <li id=\"nav_start\">\r\n");
      out.write("\t                        <a class=\"nav_a\" id=\"ricecakeNav\">\r\n");
      out.write("\t                            <i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t                            <span class=\"txt\">떡</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"nav_category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/goods_list.jsp?list=all\" class=\"category_menu\">전체보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"category_menu\">전통떡</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"category_menu\">퓨전떡</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a class=\"nav_a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/goods_list.jsp?list=best\">\r\n");
      out.write("\t                            <span class=\"txt\">베스트</span>\r\n");
      out.write("\t                        </a>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a class=\"nav_a\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/goods_list.jsp?list=new\">\r\n");
      out.write("\t                            <span class=\"txt\">신상품</span>\r\n");
      out.write("\t                        </a>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t                    <li>\r\n");
      out.write("\t                        <a class=\"nav_a\"  href=\"#\">\r\n");
      out.write("\t                            <span class=\"txt\">고객지원</span>\r\n");
      out.write("\t                        </a>\r\n");
      out.write("\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"active_btn_li\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"active_btn_wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(id==null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"userPopup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"userPopup\" id=\"userPopup_label\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fas fa-user\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fas fa-shopping-cart\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"logout_form\" action=\"/online-shopping-mall/member/signup\"  method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"logout_onclick()\"><i class=\"fas fa-sign-in-alt\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/top.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- </body>    --- index.jsp 에서 닫아줌\r\n");
      out.write("</html> -->\r\n");
      out.write("\r\n");
      out.write("<!-- test - juhong -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
