/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-20 03:14:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fside_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

		request.setCharacterEncoding("EUC-KR");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/css/admin_style.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/115bcf1f34.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \t<!-- top, bottom 제외 페이지 전체-->\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("  \r\n");
      out.write("        <header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 요약창 부분 -->\r\n");
      out.write("        <div id=\"manager_summ\">\r\n");
      out.write("              <ul id=\"manager_summ_ul\">\r\n");
      out.write("                  <li id=\"summ_first\">\r\n");
      out.write("                  \t\r\n");
      out.write("                  \t  <!-- 임시 메모  :: -->\r\n");
      out.write("                      <span style=\"font-size: 12px; color: red;\">관리자 모드의 요약창 <br/>(사용 여부: 미정 / 내용: 미정)</span>\r\n");
      out.write("                  \r\n");
      out.write("                      <div class=\"top\">\r\n");
      out.write("                          <span id=\"name\" class=\"bold\">김성진</span>\r\n");
      out.write("                          <span id=\"name_top\" class=\"text\">님</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"bottom\">\r\n");
      out.write("                          <span id=\"name_bottom\" class=\"text\">환영합니다.</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                      <div class=\"top\">\r\n");
      out.write("                          <span id=\"point_top\" class=\"text\">사용가능 포인트</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"bottom\">\r\n");
      out.write("                          <span id=\"point\" class=\"bold\">1,000</span>\r\n");
      out.write("                          <span id=\"point_bottm\" class=\"text\">원</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li id=\"summ_last\">\r\n");
      out.write("                      <div class=\"top\">\r\n");
      out.write("                          <span id=\"del_top\" class=\"text\">배송중인 주문</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"bottom\">\r\n");
      out.write("                          <span id=\"del\" class=\"bold\">2</span>\r\n");
      out.write("                          <span id=\"del_bottom\" class=\"text\">건</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"btn_manager_wrapper\">  \r\n");
      out.write("    <!-- (버튼메뉴 + manager) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div id=\"admin_side\">\r\n");
      out.write("\r\n");
      out.write("            <div id=\"section\">\r\n");
      out.write("                관리자모드\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- 메뉴 부분 -->\r\n");
      out.write("            <div id=\"manager_btn_wrapper\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <a id=\"btn_first\" href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">통계</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- chart.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">회원관리</span>\r\n");
      out.write("        \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("        \r\n");
      out.write("                            <!-- member_list.jsp / member_view.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                       \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">주문관리</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("        \r\n");
      out.write("                             <!-- order_list.jsp / order_view.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">제품관리</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- goods_master.jsp, goods_insert.jsp, goods_view.jsp, goods_stock.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">접속관리</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- 접속관리 페이지 누락됨 :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">QnA</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- qna_list.jsp / qna_view.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">공지사항</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- notice_list.jsp / notice_view.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a id=\"btn_last\" href=\"#\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span class=\"text\">FAQ</span>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- default 아이콘 -->\r\n");
      out.write("                            <span class=\"icon\"><i class=\"fas fa-chevron-left\"></i></span>\r\n");
      out.write("                        \r\n");
      out.write("                             <!-- faq_list.jsp / faq_view.jsp :: -->\r\n");
      out.write("                            <!-- <span class=\"icon\"><i class=\"fas fa-chevron-right\"></i></span> -->\r\n");
      out.write("                        \r\n");
      out.write("                        </li>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>   <!-- #btn_wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--</div>   #btn_manager_wrapper (버튼메뉴 + manager) : 하위 페이지에서 닫아야함-->\r\n");
      out.write("    \r\n");
      out.write("   <!--</div>  #main (상단요약 + 버튼 + manager) : 하위페이지에서 닫아야함-->\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
