/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-20 07:16:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import product.ProductBean;
import java.util.Vector;
import java.sql.Date;

public final class goods_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("product.ProductBean");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- goods_view.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      product.ProductMgr mgr = null;
      mgr = (product.ProductMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new product.ProductMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("EUC-KR");
	int p_code = Integer.parseInt(request.getParameter("p_code"));
	ProductBean bean = mgr.getProduct(p_code);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- <title>-관리자-제품 등록</title>  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body topmargin=\"100\">\t\r\n");
      out.write("\r\n");
      out.write("<!-- <title>-관리자-제품 등록</title> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/mypage_orderlist.css\"> -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./admin_side.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------->\r\n");
      out.write("<!--  작업 영역  -->\r\n");
      out.write("<!--------------->\r\n");
      out.write("\t\r\n");
      out.write("        <div id=\"manager\">  \r\n");
      out.write("        \r\n");
      out.write("            <h1 class=\"title\">제품 상세보기</h1>\r\n");
      out.write("\r\n");
      out.write("            <form name=\"frm\" method=\"post\" action=\"goods_Proc.jsp?flag=update\"\r\n");
      out.write("                enctype=\"multipart/form-data\" >\r\n");
      out.write("                <!-- enctype=\"multipart/form-data\" 일때에는 post방식으로 보낸다. \r\n");
      out.write("            대신에 action을 통해서 action=\"productProc.jsp?flag=insert\" 를 해줘야한다.-->        \r\n");
      out.write("        \r\n");
      out.write("        \t\t<!--  input hidden 으로 flag 값 넘기면 flag=update 전달 가능 \r\n");
      out.write("        \t\t<input type=\"hidden\" value=\"update\" name=\"flag\">\t-->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("                <h3 class=\"inner_title\">기본정보</h3>\r\n");
      out.write("                \r\n");
      out.write("                <input type=\"button\" id=\"chgread1\" value=\"수정\">\r\n");
      out.write("                \r\n");
      out.write("                            <table class=\"mgr_table verHead\">\r\n");
      out.write("        \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>제품코드</th>\r\n");
      out.write("                                    <td><input name=\"p_code\" value=\"");
      out.print(bean.getP_code());
      out.write("\" readonly>                                                            \t\r\n");
      out.write("                                    <th>제품명</th>\r\n");
      out.write("                                    <td><input class=\"1 readChange\" name=\"p_name\" value=\"");
      out.print(bean.getP_name());
      out.write("\" disabled></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>제품가격</th>\r\n");
      out.write("                                    <td><input class=\"2 readChange\" name=\"p_price\" value=\"");
      out.print(bean.getP_price());
      out.write("\" disabled>원</td>\r\n");
      out.write("                                \r\n");
      out.write("                                    <th>판매여부</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                    \t");
if(bean.getP_on_sale()==1){
      out.write("\r\n");
      out.write("                                    \t<input  class=\"3 readChange radio\" type=\"radio\" name=\"p_on_sale\" value=\"1\"checked disabled>판매\r\n");
      out.write("                                        <input  class=\"4 readChange radio\" type=\"radio\" name=\"p_on_sale\" value=\"0\" disabled>숨기기\r\n");
      out.write("                                        ");
}else{
      out.write("\r\n");
      out.write("                                        <input  class=\"3 readChange radio\" type=\"radio\" name=\"p_on_sale\" value=\"1\" disabled>판매\r\n");
      out.write("                                        <input  class=\"4 readChange radio\" type=\"radio\" name=\"p_on_sale\" value=\"0\" checked disabled>숨기기\r\n");
      out.write("                                        ");
} 
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\t\t\t\t\t\t\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>원재료(1)</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code1\" class=\"5a readChange\"disabled>\r\n");
      out.write("                                            <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                            <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"5b readChange rm_pct\" name=\"rm_percentage1\" placeholder=\"함유율\" disabled>%\r\n");
      out.write("                                    \r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <th>원재료(2)</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code2\" class=\"6a readChange\" disabled>\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"6b readChange rm_pct\" name=\"rm_percentage2\" placeholder=\"함유율\" disabled>%\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>원재료(3)</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code3\" class=\"7a readChange\" disabled>\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"7b readChange rm_pct\" name=\"rm_percentage3\" placeholder=\"함유율\" disabled>%\r\n");
      out.write("                                    </td>                                \r\n");
      out.write("                                    <th>원재료(4)</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select class=\"8a readChange\"name=\"rm_code4\" disabled>\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"8b readChange rm_pct\" name=\"rm_percentage4\" placeholder=\"함유율\" disabled>%\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("        \r\n");
      out.write("                <h3 class=\"inner_title\">사진정보</h3>\r\n");
      out.write("                            <table class=\"mgr_table verHead\" id=\"pht_table\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>메인이미지</th>\r\n");
      out.write("                                    <td>");
      out.print(bean.getP_main_pht_name());
      out.write("\r\n");
      out.write("                                    <input class=\"9 readChange\" type=\"file\" name=\"upFile1\" disabled></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>설명이미지</th>                                                                    \r\n");
      out.write("                                    <td> ");
      out.print(bean.getP_detail_pht_name());
      out.write("\r\n");
      out.write("                                    <input class=\"10 readChange\" type=\"file\" name=\"upFile2\" disabled></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>상세이미지</th>\r\n");
      out.write("                                    <td> ");
      out.print(bean.getP_info_pht_name());
      out.write("\r\n");
      out.write("                                    <input class=\"11 readChange\" type=\"file\" name=\"upFile3\" disabled></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("            <div class=\"submit_wrapper\">\r\n");
      out.write("                <input class=\"btn\" type=\"button\" value=\"목록으로\" onclick=\"location.href='goods_master.jsp'\">\r\n");
      out.write("                <input class=\"btn readChange\" type=\"submit\" value=\"수정완료\" disabled>                \r\n");
      out.write("                <input class=\"btn\" type=\"button\" value=\"삭제하기\" onclick=\"location.href='goods_Proc.jsp?flag=delete&pcode=");
      out.print(bean.getP_code());
      out.write("'\">\r\n");
      out.write("                <input class=\"btn\" type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("                <input type=\"hidden\"  value=\"");
      out.print(bean.getP_code());
      out.write("\" name=\"pcode\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </form>        \r\n");
      out.write("        </div>\t\t\r\n");
      out.write("<!----------------->\r\n");
      out.write("<!--  작업 영역 끝 -->\r\n");
      out.write("<!----------------->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!--  #btn_manager_wrapper (버튼메뉴 + manager) : admin_side.jsp 에서 열림-->\r\n");
      out.write("</div> <!-- #main (상단요약 + 버튼 + manager) : admin_side.jsp 에서 열림-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../bottom.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tfunction btnInit(){\r\n");
      out.write("\t\t\tconst button = document.querySelector('#chgread1');\r\n");
      out.write("\t\t\tlet flag = 0;\r\n");
      out.write("\t\t\tbutton.addEventListener('click', function(){\r\n");
      out.write("\t\t\t\tconst reads = document.querySelectorAll('.readChange');\r\n");
      out.write("\t\t\t\tif(flag===0){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"DDD\");\r\n");
      out.write("\t\t\t\t\treads.forEach(function(items){\r\n");
      out.write("\t\t\t\t\t\titems.disabled = false;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tflag = 1;\r\n");
      out.write("\t\t\t\t\tbutton.value = '해제';\r\n");
      out.write("\t\t\t\t\tconsole.log(button);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\treads.forEach(function(items){\r\n");
      out.write("\t\t\t\t\t\titems.disabled = true;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tflag = 0;\r\n");
      out.write("\t\t\t\t\tconsole.log(\"FFF\");\r\n");
      out.write("\t\t\t\t\tbutton.value = '수정';\r\n");
      out.write("\t\t\t\t\tconsole.log(button);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbtnInit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
