/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-20 04:09:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Date;

public final class goods_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- goods_insert.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("EUC-KR");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- <title>-관리자-제품 등록</title> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/mypage_orderlist.css\"> -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./admin_side.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--------------->\r\n");
      out.write("<!--  작업 영역  -->\r\n");
      out.write("<!--------------->\r\n");
      out.write("\t\r\n");
      out.write("        <div id=\"manager\">  \r\n");
      out.write("        \r\n");
      out.write("            <h1 class=\"title\">제품 등록</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"goods_Proc.jsp?flag=insert\"\r\n");
      out.write("\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<!-- enctype=\"multipart/form-data\" 일때에는 post방식으로 보낸다. \r\n");
      out.write("\t\t\t대신에 action을 통해서 action=\"productProc.jsp?flag=insert\" 를 해줘야한다.-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <h3 class=\"inner_title\">기본정보</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <table class=\"mgr_table verHead\">\r\n");
      out.write("        \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>제품코드</td>\r\n");
      out.write("                                    <td><input name=\"p_code\" placeholder=\"자동생성됩니다.\" readonly></td>\r\n");
      out.write("                                \r\n");
      out.write("                                    <th>제품명</td>\r\n");
      out.write("                                    <td><input name=\"p_name\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>제품가격</td>\r\n");
      out.write("                                    <td><input name=\"p_price\">원</td>\r\n");
      out.write("                                \r\n");
      out.write("                                    <th>판매여부</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input class=\"radio\" type=\"radio\" name=\"p_on_sale\" value=\"1\">판매\r\n");
      out.write("                                        <input class=\"radio\" type=\"radio\" name=\"p_on_sale\" value=\"0\" checked>숨기기\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\t\t\t\t\t\t\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>원재료(1)</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code1\">\r\n");
      out.write("                                            <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                            <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"rm_pct\" name=\"rm_percentage1\" placeholder=\"함유율\">%\r\n");
      out.write("                                    \r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <th>원재료(2)</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code2\">\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"rm_pct\" name=\"rm_percentage2\" placeholder=\"함유율\">%\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>원재료(3)</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code3\">\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"rm_pct\" name=\"rm_percentage3\" placeholder=\"함유율\">%\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                \r\n");
      out.write("                                    <th>원재료(4)</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <select name=\"rm_code4\">\r\n");
      out.write("                                                <option value=\"\" disabled selected>원재료명</option>\r\n");
      out.write("                                                <option value=\"\"></option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <input class=\"rm_pct\" name=\"rm_percentage4\" placeholder=\"함유율\">%\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("        \r\n");
      out.write("                <h3 class=\"inner_title\">사진정보</h3>\r\n");
      out.write("                            <table class=\"mgr_table verHead\" id=\"pht_table\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>메인이미지</td>\r\n");
      out.write("                                    <td><input type=\"file\" name=\"upFile1\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>설명이미지</td>\r\n");
      out.write("                                    <td><input type=\"file\" name=\"upFile2\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>상세이미지</td>\r\n");
      out.write("                                    <td><input type=\"file\" name=\"upFile3\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"submit_wrapper\">\r\n");
      out.write("                <input class=\"btn\" type=\"submit\" value=\"상품등록\">\r\n");
      out.write("                <input class=\"btn\" type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        \r\n");
      out.write("        </div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!----------------->\r\n");
      out.write("<!--  작업 영역 끝 -->\r\n");
      out.write("<!----------------->\r\n");
      out.write("\t\r\n");
      out.write("</div> <!--  #btn_manager_wrapper (버튼메뉴 + manager) : admin_side.jsp 에서 열림-->\r\n");
      out.write("</div> <!-- #main (상단요약 + 버튼 + manager) : admin_side.jsp 에서 열림-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../bottom.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
